spring:
  application:
    name: musinsa-homework
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=SET REFERENTIAL_INTEGRITY FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 1000
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080
