spring:
  application:
    name: musinsa-homework
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080
